name: Feature request
description: Suggest an improvement to Khabeer
title: '[Feature]: '
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem should this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Suggested behavior and alternatives
    validations:
      required: true
